from django.db import models

class MonthAnalysis(models.Model):
    keyword = models.TextField()
    total = models.IntegerField()
    pc = models.IntegerField()
    mobile = models.IntegerField()
    male = models.IntegerField()
    female = models.IntegerField()
    key10a = models.CharField(max_length=5)
    key10b = models.CharField(max_length=5)
    key20a = models.CharField(max_length=5)
    key20b = models.CharField(max_length=5)
    key30 = models.CharField(max_length=5)
    key40 = models.CharField(max_length=5)
    key50 = models.CharField(max_length=5)
    m_10a = models.IntegerField()
    m_10b = models.IntegerField()
    m_20a = models.IntegerField()
    m_20b = models.IntegerField()
    m_30 = models.IntegerField()
    m_40 = models.IntegerField()
    m_50 = models.IntegerField()
    f_10a = models.IntegerField()
    f_10b = models.IntegerField()
    f_20a = models.IntegerField()
    f_20b = models.IntegerField()
    f_30 = models.IntegerField()
    f_40 = models.IntegerField()
    f_50 = models.IntegerField()
    key_month1 = models.DateField()
    key_month2 = models.DateField()
    key_month3 = models.DateField()
    key_month4 = models.DateField()
    key_month5 = models.DateField()
    key_month6 = models.DateField()
    key_month7 = models.DateField()
    key_month8 = models.DateField()
    key_month9 = models.DateField()
    key_month10 = models.DateField()
    key_month11 = models.DateField()
    key_month12 = models.DateField()
    key_month13 = models.DateField()
    pc_month1 = models.IntegerField()
    pc_month2 = models.IntegerField()
    pc_month3 = models.IntegerField()
    pc_month4 = models.IntegerField()
    pc_month5 = models.IntegerField()
    pc_month6 = models.IntegerField()
    pc_month7 = models.IntegerField()
    pc_month8 = models.IntegerField()
    pc_month9 = models.IntegerField()
    pc_month10 = models.IntegerField()
    pc_month11 = models.IntegerField()
    pc_month12 = models.IntegerField()
    pc_month13 = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)



